language: python
# ===== Linux ======
os: linux
dist: bionic
python:
  - 3.8
install:
  - pip install -r python/requirements.txt
  - pip install pytest-cov
script:
  - export PYTHONPATH=$PYTHONPATH:$(realpath python/)
  - pytest --cov --cov-report xml python/
